# Generated by Django 3.0.2 on 2021-03-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image1', models.ImageField(default='', upload_to='shop/images')),
                ('header_image2', models.ImageField(default='', upload_to='shop/images')),
                ('header_image3', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
