# Generated by Django 3.0.2 on 2021-03-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_design'),
    ]

    operations = [
        migrations.RenameField(
            model_name='design',
            old_name='header_image1',
            new_name='header',
        ),
        migrations.RemoveField(
            model_name='design',
            name='header_image2',
        ),
        migrations.RemoveField(
            model_name='design',
            name='header_image3',
        ),
    ]
