# Generated by Django 3.0.2 on 2021-03-14 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210315_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyForm',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
            ],
            bases=('shop.product',),
        ),
    ]
