# Generated by Django 3.0.2 on 2021-03-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_myform'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='banner',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
